### ISSUE TITLE
Feedback from Optional Format Review

### ISSUE THREAD

**Issue by danjardin** [matthewfeickert/Dedman-Thesis-Latex-Template#52]
There were only 5 issues returned from the first optional thesis format review, which means this template is already doing a great job. Here is the list of requested modifications:

- [x] **Check top margins of pre-pages (Issue #54):** They specifically referenced pg.7 of the [Dissertation and Thesis Guide](https://www.smu.edu/graduate/CurrentStudents/Graduation/DissThesisGuide).
- [x]  **Committee members and positions should be single-spaced on signature page (Issue #55):** It seems to be double-spaced if their name or title spills onto a second line.
- [x] **Title of abstract should not be all caps, only capitalize first letter of important words (Issue #56):** However, the thesis title on the title page should still be all caps. I suggest setting both of these with the template regardless of how the user writes the title in `user_config.tex`
- [x] **Avoid orphans (Issue #57):** This might require some digging because the easiest way to avoid orphans & widows is to add `\usepackage[all]{nowidow}`, which has already been included since it was requested in Issue #11. (:x: This was abandoned as section titles are too finicky)
- [x] **Indent after the first line of each bib citation (Issue #58):** This is called a hanging indent, and needs to be applied to the bibliography despite the fact that the bib entries are already numbered and effectively look like a hanging indent already.

**Comment by matthewfeickert** [comment]
@danjardin Thanks for the very detailed and helpful feedback. :+1: 

The mandatory thesis style check is March 28th for you, but does it need to be 100% passing? Or if it is mostly implemented would that be alright?

**Comment by danjardin** [comment]
There's one more final format check on April 19th that will need to pass 100%, but I would guess it's okay if this next round doesn't

**Comment by matthewfeickert** [comment]
> ... but I would guess it's okay if this next round doesn't

This should be doable before then, but the next 5 days are going to be extremely busy.

**Comment by matthewfeickert** [comment]
> **Indent after the first line of each bib citation:** This is called a hanging indent, and needs to be applied to the bibliography despite the fact that the bib entries are already numbered and effectively look like a hanging indent already.

@danjardin This is the only one I'm not really clear on. I guess I'm not sure what they are supposed to look like. Are they just supposed to be indented more? @Alkusoittow @egodat I'm going to ask if you have clarification on this as well.

**Comment by matthewfeickert** [comment]
> **Title of abstract should not be all caps, only capitalize first letter of important words:** However, the thesis title on the title page should still be all caps. I suggest setting both of these with the template regardless of how the user writes the title in `user_config.tex`

@danjardin I'm not sure if this is possible to enforce at the template level. There is no way to know what are the proper nouns that should be capitalized. You can only universally enforce a style (e.g., all caps). So the user should write their title in `user_config.tex` in the way that they want it to be shown in the abstract.

**Comment by danjardin** [comment]
> > **Indent after the first line of each bib citation:** This is called a hanging indent, and needs to be applied to the bibliography despite the fact that the bib entries are already numbered and effectively look like a hanging indent already.
> 
> @danjardin This is the only one I'm not really clear on. I guess I'm not sure what they are supposed to look like. Are they just supposed to be indented more?

I'm not fluent in bib styles, but [this post](https://tex.stackexchange.com/questions/288205/hanging-indent-for-bibliography-items) shows an example of what the hanging indents should look like, except that our bib will still be numbered.

**Comment by danjardin** [comment]
> There is no way to know what are the proper nouns that should be capitalized. You can only universally enforce a style (e.g., all caps). So the user should write their title in `user_config.tex` in the way that they want it to be shown in the abstract.

I sort of realized this as I was writing it too. I think that's the right approach, and maybe add a comment to the file letting the user know that this is the case so they should be careful to write it the way they want it to be.

**Comment by matthewfeickert** [comment]
> I'm not fluent in bib styles, but [this post](https://tex.stackexchange.com/questions/288205/hanging-indent-for-bibliography-items) shows an example of what the hanging indents should look like, except that our bib will still be numbered.

Ah okay. I understand now: it is RE: the second line of the entry as is done in the figure list

![figure_list](https://user-images.githubusercontent.com/5142394/54862116-222f9200-4d0c-11e9-9ebe-7d188870d4c2.png)

**Comment by matthewfeickert** [comment]
> maybe add a comment to the file letting the user know that this is the case so they should be careful to write it the way they want it to be.

Yup, already did this (seems we're on the same page :slightly_smiling_face:). It will show up in the PR for this (I think I'll keep them as separate commits no squashing this time).

**Comment by matthewfeickert** [comment]
> **Check top margins of pre-pages:** They specifically referenced pg.7 of the [Dissertation and Thesis Guide](https://www.smu.edu/graduate/CurrentStudents/Graduation/DissThesisGuide).

The thesis guide says that

>The following pages require a 2" top margin
>- Signature Page
>- Title Page
>- Copyright Page
>- Acknowledgment Page
>- Lists (first page of each only)
>- Chapter heading pages in text
>- Appendix (first page only)
>- Bibliography (first page only)
>All other margins should be 1" from the edge of the page – top, bottom, left, and right. Tables, figures, and appendices follow the same margin rules as the main text.

So I assume that the only thing that is needed is to set a 2 inch margin on those pages.

**Comment by matthewfeickert** [comment]
@danjardin Can you take a look at the below and let me know if that looks okay?

![single_spaced_committee](https://user-images.githubusercontent.com/5142394/54976378-2e179000-4f68-11e9-9f4d-825ac066f1ac.png)

**Comment by danjardin** [comment]
Yep, that looks single-spaced to me.

Side note: This order of signatures makes more sense to me, but I read in the guidebook recently that the committee members are supposed to be alphabetical by last name (after advisor first). That's obviously not something you can change in the template (that I know of), but something to be aware of.

**Comment by matthewfeickert** [comment]
> Side note: This order of signatures makes more sense to me, but I read in the guidebook recently that the committee members are supposed to be alphabetical by last name (after advisor first). That's obviously not something you can change in the template (that I know of), but something to be aware of.

It looks like @jhetherly and @egodat were able to escape this alphabetical order rule, so it might not really be enforced. If it is, we can still change the template to hint at this by having their last names be something like "Alphabetical", "Order", "Used".

**Comment by matthewfeickert** [comment]
> **Avoid orphans:** This might require some digging because the easiest way to avoid orphans & widows is to add `\usepackage[all]{nowidow}`...

@danjardin As I currently don't have any widowed subsection headings as you do can you try [using the following](https://tex.stackexchange.com/a/4167/152544) somewhere in the preamble

```
\widowpenalty=10000
\clubpenalty=10000
```

and report back what happens?

**Comment by egodat** [comment]
I used nowidow in my thesis

On Mar 26, 2019, at 3:59 PM, Matthew Feickert <notifications@github.com<mailto:notifications@github.com>> wrote:


Avoid orphans: This might require some digging because the easiest way to avoid orphans & widows is to add \usepackage[all]{nowidow}...

@danjardin<https://github.com/danjardin> As I currently don't have any widowed subsection headings as you do can you try using the following<https://tex.stackexchange.com/a/4167/152544> somewhere in the preamble

\widowpenalty=10000
\clubpenalty=10000


and report back what happens?

**Comment by matthewfeickert** [comment]
> I used `nowidow` in my thesis

@egodat Yes, but that has been included in the template since PR #14, and as @Alkusoittow points out it doesn't protect against widowed/orphaned subsection headings, which is what @danjardin is experiencing at the moment.

Using
```
\widowpenalty=10000
\clubpenalty=10000
```

should (I think) tell LaTeX to treat these penalties as the worst possible and force it to avoid them. What I want @danjardin to test is if it does so at a horrible price of breaking all other formatting.

**Comment by egodat** [comment]
I experienced the same thing with the headings. After a lot of trial and error with different settings was to ignore it and once I finished writing, manually pagebreak the offending headings. Because sometimes the fastest way gets a result :P

On Mar 26, 2019, at 5:07 PM, Matthew Feickert <notifications@github.com<mailto:notifications@github.com>> wrote:


I used nowidow in my thesis

@egodat<https://github.com/egodat> Yes, but that has been included in the template since PR #14<https://github.com/matthewfeickert/Dedman-Thesis-Latex-Template/pull/14>, and as @Alkusoittow<https://github.com/Alkusoittow> points out it doesn't protect against widowed/orphaned subsection headings, which is what @danjardin<https://github.com/danjardin> is experiencing at the moment.

Using

\widowpenalty=10000
\clubpenalty=10000


should (I think) tell LaTeX to treat these penalties as the worst possible and force it to avoid them. What I want @danjardin<https://github.com/danjardin> to test is if it does so at a horrible price of breaking all other formatting.

**Comment by Alkusoittow** [comment]
That was exactly what I did. Once I had a “final” version, I manually did page breaks for section headings...



On Mar 26, 2019, at 5:38 PM, Eric Godat <notifications@github.com<mailto:notifications@github.com>> wrote:

I experienced the same thing with the headings. After a lot of trial and error with different settings was to ignore it and once I finished writing, manually pagebreak the offending headings. Because sometimes the fastest way gets a result :P

On Mar 26, 2019, at 5:07 PM, Matthew Feickert <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


I used nowidow in my thesis

@egodat<https://github.com/egodat> Yes, but that has been included in the template since PR #14<https://github.com/matthewfeickert/Dedman-Thesis-Latex-Template/pull/14>, and as @Alkusoittow<https://github.com/Alkusoittow> points out it doesn't protect against widowed/orphaned subsection headings, which is what @danjardin<https://github.com/danjardin> is experiencing at the moment.

Using

\widowpenalty=10000
\clubpenalty=10000


should (I think) tell LaTeX to treat these penalties as the worst possible and force it to avoid them. What I want @danjardin<https://github.com/danjardin> to test is if it does so at a horrible price of breaking all other formatting.

**Comment by matthewfeickert** [comment]
> After a lot of trial and error with different settings was to ignore it and once I finished writing, manually pagebreak the offending headings. Because sometimes the fastest way gets a result.

> Once I had a “final” version, I manually did page breaks for section headings...

@egodat @Alkusoittow Thanks for the feedback! @danjardin This was what I had assumed that people would do, as this is what I have always done with both my own work and ATLAS papers. 

I'm 100% fine with having people be responsible for not allowing widows/orphans in their own thesis, but I figure if we can make it even more rare for these edge cases to happen then that's a good thing to "enforce" through the template as long as it doesn't put pressure in other style areas.

**Comment by egodat** [comment]
The template also really struggled with section headings when the entirety of the section was figures (several of my appendices). If you have similar problems, I can look back at what I had to do to make it work correctly.

On Mar 26, 2019, at 7:54 PM, Matthew Feickert <notifications@github.com<mailto:notifications@github.com>> wrote:


After a lot of trial and error with different settings was to ignore it and once I finished writing, manually pagebreak the offending headings. Because sometimes the fastest way gets a result.

Once I had a “final” version, I manually did page breaks for section headings...

@egodat<https://github.com/egodat> @Alkusoittow<https://github.com/Alkusoittow> Thanks for the feedback! @danjardin<https://github.com/danjardin> This was what I had assumed that people would do, as this is what I have always done with both my own work and ATLAS papers.

I'm 100% fine with having people be responsible for not allowing widows/orphans in their own thesis, but I figure if we can make it even more rare for these edge cases to happen then that's a good thing to "enforce" through the template as long as it doesn't put pressure in other style areas.

**Comment by matthewfeickert** [comment]
Even with playing around with `\widowpenalty` and `\clubpenalty` I couldn't get the template to overcome issues with orphaned section titles.

@danjardin I'm just going to recommend that everyone follow the advice of [TeX FAQ RE: widows and orphans](https://texfaq.org/FAQ-widows). I'll put in text in the template RE: this.

**Comment by danjardin** [comment]
> Even with playing around with `\widowpenalty` and `\clubpenalty` I couldn't get the template to overcome issues with orphaned section titles.

You got to this quicker than me (I had to artificially force a new orphan), but I also could not solve it with `\widowpenalty` and `\clupenalty`. It's unfortunate that `\nowidow` is so limited, but I will reluctantly join you in manually forcing page breaks.

**Comment by matthewfeickert** [comment]
> It's unfortunate that `\nowidow` is so limited, but I will reluctantly join you in manually forcing page breaks.

Yeah, I think it is actually doing a very good job of making sure that _normal text_ doesn't create widows/orphans, but given that sections are their own environments that behave differently I think it has a harder time knowing how to deal with them.

I guess the "good" news is that this is really only a chapter by chapter issue, and not a document wide issue.

**Comment by danjardin** [comment]
> I guess the "good" news is that this is really only a chapter by chapter issue, and not a document wide issue.

Yes absolutely! I cringed when first hearing the proposal to do it manually until I realized that each chapter/appendix stands alone. I'm sure SMU looks for this in their series of format checks, but I'll make a note to myself to do this later when my chapters aren't in constant flux.

**Comment by danjardin** [comment]
> the only thing that is needed is to set a 2 inch margin on those pages.

I'l take a stab at proposing a solution that you can implement. [This page](https://www.overleaf.com/learn/latex/Page_size_and_margins) is a helpful reference for defining all the parameters that control the page layout. It seems there are two reasonable fixes offered to [this question](https://stackoverflow.com/questions/1670463/latex-change-margins-of-only-a-few-pages).

**Quick fix**: needs to be added to each page and can be customized to whatever the individual requirements are for that page.
`\newgeometry{top=2in}`
Page text
`\restoregeometry`

**Broad fix**: create a new environment command in a central place and call it for each page that needs formatting. This can be expanded to change more than one parameter.
`\newenvironment{changemargin}[1]{`
`\begin{list}{}{`
`\setlength{\voffset}{#1}`
`}`
`\item[]}{\end{list}}`

Then to call this command on a page:
`\begin{changemargin}{-2in}`
Page text
`\end{changemargin}`

**Comment by danjardin** [comment]
> the user should write their title in `user_config.tex` in the way that they want it to be shown in the abstract.

@matthewfeickert I just have one more thing to add about the title in `user_config.tex`. The title can be 3 lines, so you've included `{}{}{}` to manually separate the lines. However, I made the mistake of deleting one set of brackets when I shortened my title to 2 lines and got an error. This is probably just another line of comment, but unused brackets need to be left empty if the title is <3 lines.

PS - The checklist at the top works fine, but I regret not opening separate issues because this thread is allllll over the place!

**Comment by matthewfeickert** [comment]
> Since we only need to change one parameter for a handful of pages, I think the "Quick Fix" seems like the better solution.

I think the solution that uses the `geometry` package seems more "on brand"/"in the style" of LaTeX anyway, so we're in agreement.

> This is probably just another line of comment, but unused brackets need to be left empty if the title is <3 lines.

Yes, I thought that the existence of the empty brackets would signal this, but I can just add a comment in.

>  I regret not opening separate issues because this thread is allllll over the place!

Separate issues are almost always the way to go :+1:, but I didn't want to ask you to go through the work of breaking them out.

I'm not saying this is a good thing, but I've been in GitHub discussions that have lasted for months and those discussions get beastly fast. Still better than JIRA though. :sunglasses:

**Comment by matthewfeickert** [comment]
@danjardin I went ahead and said screw it and made a project for to split this all out and keep it organized. Please make an Issue for each of the issues that were brought up and I'll split off PR #53 into individual PRs that will close them. This should keep things much more manageable, given that the scope of the PR as is can no longer truly be called "atomic".

This is a bit more work for both of us, but it will be easier for everyone in the long run.

**Comment by matthewfeickert** [comment]
It is done!
